import { createRequestHandler, type ServerBuild } from '@remix-run/cloudflare'

import type { Env } from './app/env'
import { getLoadContext } from './load-context'

// @ts-expect-error the server build is generated by `remix vite:build`
import * as build from './build/server'

const handleRemixRequest = createRequestHandler(build as ServerBuild)

/** Cloudflare's `fetch` handler contract, without pulling in the DOM-clashing global types. */
interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void
  passThroughOnException(): void
}

/**
 * The Worker.
 *
 * Static assets are served *before* this runs — `assets.run_worker_first`
 * defaults to false — so a request only reaches here when no file in
 * `build/client` matches it. That is exactly the fallthrough SSR needs, and it
 * is why `assets.not_found_handling` must stay at its default: setting it to
 * `single-page-application` would answer every unmatched route with index.html
 * and this handler would never run at all.
 */
export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    try {
      return await handleRemixRequest(
        request,
        getLoadContext({ request, context: { cloudflare: { env, ctx } } }),
      )
    } catch (error) {
      console.error(error)
      return new Response('An unexpected error occurred', { status: 500 })
    }
  },
}
